// ============================================
// TESTIMONIALS DATA — Auto-generated by Admin Panel
// Generated: 30/6/2026, 00.02.32
// ============================================

const TESTIMONIALS = [
  { url: "https://i.ibb.co/hx4fv7dw/Testimoni-29062026.png", alt: "Testimoni 29062026" }
];

// Interval slide otomatis (dalam milidetik)
const SLIDE_INTERVAL = 5000;
