// ============================================
// TESTIMONIALS DATA — Auto-generated by Admin Panel
// Generated: 30/6/2026, 00.00.24
// ============================================

const TESTIMONIALS = [
  { url: "images/testimonials/Testimoni 29062026.png", alt: "Testimoni 29062026" }
];

// Interval slide otomatis (dalam milidetik)
const SLIDE_INTERVAL = 5000;
