// ============================================
// TESTIMONIALS DATA — Auto-generated by Admin Panel
// Generated: 29/6/2026, 19.56.28
// ============================================

const TESTIMONIALS = [
  { url: "https://i.ibb.co/Nn2rrL3P/photo-6201771568581513606-w.jpg", alt: "photo_6201771568581513606_w" },
  { url: "https://i.ibb.co/S7BWJY6J/photo-6201771568581513603-w.jpg", alt: "photo_6201771568581513603_w" },
  { url: "images/testimonials/photo_6201771568581513604_w.jpg", alt: "photo_6201771568581513604_w" },
  { url: "images/testimonials/photo_6201771568581513605_w.jpg", alt: "photo_6201771568581513605_w" }
];

// Interval slide otomatis (dalam milidetik)
const SLIDE_INTERVAL = 5000;
